### ISSUE TITLE
please, update bevy 0.11

### ISSUE THREAD

**Issue by taiyoungjang** [Bluefinger/bevy_rand#7]
Need update bevy version.
Thanks.

**Comment by Bluefinger** [comment]
In due time! Kinda hard to make an update when bevy releases while I am sleeping. I'll be updating my bevy crates in short order, and I'll be doing a few additions to `bevy_rand` as well.

**Comment by Bluefinger** [comment]
Due to https://github.com/bevyengine/bevy/pull/7184, it seems I'm blocked on moving forward with any quick updates. I will be needing to rewrite/rearchitect this plugin because of the new requirements for reflection pretty much blocking what I've done here, and forcing users of this crate to have to newtype all their RNGs is a bit much. No ETA on when an update will happen, just that I'm working on it (and it will also require a big change on the documentation as well)

**Comment by Bluefinger** [comment]
Closing this as v0.2 has since been released
